In [ ]:
# --- Indexing

In [ ]:
# --- 1D Array

In [1]:
import numpy as np

In [24]:
first_element = array_1d[0]
print("\nFirst Element of 1D Array:", first_element)

# Access the last element
last_element = array_1d[-1]
print("Last Element of 1D Array:", last_element)


First Element of 1D Array: 10
Last Element of 1D Array: 50


In [ ]:
# --- 2D Array

In [26]:
element_2d = array_2d[1, 2]
print("\nElement at Row 1, Column 2 in 2D Array:", element_2d)

second_row = array_2d[1]
print("Second Row of 2D Array:", second_row)


Element at Row 1, Column 2 in 2D Array: 6
Second Row of 2D Array: [4 5 6]


In [ ]:
# --- 3D Array

In [28]:
element_3d = array_3d[1, 0, 1]
print("\nElement at Depth 1, Row 0, Column 1 in 3D Array:", element_3d)

first_layer = array_3d[0]
print("First Layer of 3D Array:\n", first_layer)


Element at Depth 1, Row 0, Column 1 in 3D Array: 6
First Layer of 3D Array:
 [[1 2]
 [3 4]]


In [ ]:
# --- Slicing

In [ ]:
# --- 1D Array

In [30]:
slice_1d = array_1d[1:4]
print("\nSlice of 1D Array (Index 1 to 3):", slice_1d)

# Slice the last two elements
last_two_elements = array_1d[-2:]
print("Last Two Elements of 1D Array:", last_two_elements)


Slice of 1D Array (Index 1 to 3): [20 30 40]
Last Two Elements of 1D Array: [40 50]


In [ ]:
# --- 1D Array

In [32]:
slice_2d = array_2d[0:2, 0:2]
print("\nSlice of 2D Array (First Two Rows and Columns):\n", slice_2d)

# Slice the entire second column
second_column = array_2d[:, 1]
print("Second Column of 2D Array:", second_column)


Slice of 2D Array (First Two Rows and Columns):
 [[1 2]
 [4 5]]
Second Column of 2D Array: [2 5 8]


In [ ]:
# --- 3D Array

In [34]:
slice_3d = array_3d[0:2, 0, :]
print("\nSlice of 3D Array (First Two Layers, First Row):\n", slice_3d)

# Slice to get all elements in the last layer
last_layer = array_3d[-1, :, :]
print("Last Layer of 3D Array:\n", last_layer)


Slice of 3D Array (First Two Layers, First Row):
 [[1 2]
 [5 6]]
Last Layer of 3D Array:
 [[ 9 10]
 [11 12]]
