In [ ]:
# --- Reshape

In [5]:
import numpy as np

In [11]:
array_1d = np.array([1, 2, 3, 4, 5, 6])
print("1D Array:", array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)

array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D Array:\n", array_3d)

1D Array: [1 2 3 4 5 6]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# --- Reshaping 1D Array to 2D

In [9]:
reshaped_array = array_1d.reshape(2, 3)
print("\nReshaped Array (1D to 2D):\n", reshaped_array)


Reshaped Array (1D to 2D):
 [[1 2 3]
 [4 5 6]]


In [ ]:
# --- Reshaping 2D Array to 3D

In [13]:
reshaped_3d = array_2d.reshape(2, 3, 1)
print("\nReshaped Array (2D to 3D):\n", reshaped_3d)


Reshaped Array (2D to 3D):
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# --- Transpose

In [ ]:
# --- Transposing 2D Array

In [15]:
transposed_array = array_2d.T
print("\nTransposed 2D Array:\n", transposed_array)


Transposed 2D Array:
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# --- Transposing 3D Array

In [17]:
transposed_3d = np.transpose(array_3d, (1, 0, 2))
print("\nTransposed 3D Array:\n", transposed_3d)


Transposed 3D Array:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
# --- Concatenate

In [ ]:
# --- Concatenating 1D Array

In [19]:
array_1d_b = np.array([7, 8, 9])

concatenated_1d = np.concatenate((array_1d, array_1d_b))
print("\nConcatenated 1D Array:", concatenated_1d)


Concatenated 1D Array: [1 2 3 4 5 6 7 8 9]


In [ ]:
# --- Concatenating 2D Arrays

In [21]:
array_2d_b = np.array([[7, 8, 9], [10, 11, 12]])

concatenated_2d_rows = np.concatenate((array_2d, array_2d_b), axis=0)
print("\nConcatenated 2D Array along Rows:\n", concatenated_2d_rows)

concatenated_2d_cols = np.concatenate((array_2d, array_2d_b), axis=1)
print("\nConcatenated 2D Array along Columns:\n", concatenated_2d_cols)


Concatenated 2D Array along Rows:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Concatenated 2D Array along Columns:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
